### ISSUE TITLE
WCA data in profiles

### ISSUE THREAD

**Issue by jbcm627** [cubing/ccm#100]
A few things we can do:
 - [ ] Suggest WCA ids based on name (and perhaps autofill fields?)
 - [ ] Point out any conflicts (but don't enforce consistency with the WCA dabase; data may not be synced with WCA db, and perhaps a competitor wants to change their name anyways?

**Comment by jfly** [comment]
Closing this in favor of oauth with the wca website. There's also dealing with people who register onsite, but I think it would be better to document an API for searching for people. This could even let us get bdays, because we could use the oauth credentials of the delegate for the competition.
