### ISSUE TITLE
Display statistics vs time for registrations, users, and competitions

### ISSUE THREAD

**Issue by jbcm627** [cubing/ccm#102]
Could be neat to see.

**Comment by jfly** [comment]
Jim, what is this issue for? I honestly cannot remember.

**Comment by jbcm627** [comment]
This should be a WCA website thing now. Maybe I had in mind something like this:
https://www.worldcubeassociation.org/results/misc/evolution/
but for individuals, or really any of the [statistics](https://www.worldcubeassociation.org/results/statistics.php) vs time.
