### ISSUE TITLE
How to handle competitors who do not show up for a round?

### ISSUE THREAD

**Issue by jfly** [cubing/ccm#107]
If organizers cannot do this, then their round completion progress bars will never be accurate. We will also end up giving them warnings about the number of people who advanced to a round, when there really shouldn't be a warning, because they didn't compete (see  https://www.worldcubeassociation.org/regulations/#9p3).

**Comment by jfly** [comment]
Cubecomps's solution: https://www.speedsolving.com/forum/showthread.php?35560-cubecomps-com-for-delegates-and-organizers&p=769182&viewfull=1#post769182

**Comment by jbcm627** [comment]
Related: 3rd comment in #90.  (How about adding competitors to a round without needing to navigate away from the data entry page?)

**Comment by jfly** [comment]
Dumping some ideas...

I think we'll add a "no show" button or toggle. Clicking it will copy over the first competitor who didn't advance from the previous round. It will still be possible to enter times for a person who was marked "no-show", but doing so will require marking them as not a no show =). We need to make sure that when someone is marked no-show for the 2nd time, we don't advance someone from the previous round again.

**Comment by jfly** [comment]
As of 458dff6c54e0a34792731f32b7553493bea9e58c, we now correctly update rounds with their size, so we can use that to enforce that the correct number of people are in the round as we mark/unmark them as `noShow`.

**Comment by jfly** [comment]
Notify organizers about the fact that we've advanced someone.

**Comment by jfly** [comment]
After talking with @FatBoyXPC, we decided it would be best to just ask the organizer if they want to advance someone. This solves all the problems we agonized about above.
