### ISSUE TITLE
Notify competitors of new nearby competitions

### ISSUE THREAD

**Issue by jbcm627** [cubing/ccm#108]
Via emails or something.  This is blocked by #96.

Allow users to unsubscribe too.  Perhaps have a button organizers can click to "announce", once location is set?  Or should this be admins only?  Or automated?

**Comment by jfly** [comment]
I was thinking that this sort of thing would be driven by a site admin marking a competition as "visible". 

I still do feel like this sort of thing should be done by the wca website, though.

**Comment by jbcm627** [comment]
Hmm, yeah I agree this should be implemented by the WCA website.

I'll make an issue there and close this one once development there seems to be headed in a certain direction.
