### ISSUE TITLE
User profile pictures

### ISSUE THREAD

**Issue by jbcm627** [cubing/ccm#110]
Is this feature of any interest?  Should we have some sort of reporting system too then?

What about taking WCA profile photos?

**Comment by jfly** [comment]
This sounds pretty. It would be *really* cool if we were oauthing to the wca website and using the profile pictures there, though.

**Comment by limabeans** [comment]
should this be on the competitorResults page? I made a link to their WCA profile that page, although in a (hacky) way:

    wcaProfileUrl: function() {
	var wcaId = this.registration.wcaId;
	return 'https://www.worldcubeassociation.org/results/p.php?i='+wcaId;
    }


lol.

**Comment by jfly** [comment]
Lets not hotlink to the WCA profile images for now.

**Comment by coder13** [comment]
Irrelevant now.
