### ISSUE TITLE
Event Icons

### ISSUE THREAD

**Issue by jbcm627** [cubing/ccm#114]
@keemy, the icons are yours, right?  Any interest in making special bld/oh/... ones?

Or we could ask Baiqiang about using the CubingChina ones:
http://cubingchina.com/f/images/events-icon-half.png

**Comment by jbcm627** [comment]
Also @keemy, any interest in making a font out of these?  @jfly came across a neat service that seems like it can make a font out of svgs:
http://fontastic.me/

Maybe give this its own repo too; I'm certain other places would use this.

**Comment by keemy** [comment]
yeah i had plans about doing some stuff witht hem at some point, that service looks like it could actually  help a lot. just wondering if you have any ideas other than just sticking a foot/hand/etc. on them? (like for blind making them grey and regular events making them different colors)

**Comment by jfly** [comment]
Ah, coloring is one argument against making font set of icons.

**Comment by jbcm627** [comment]
Or an argument for it... isn't coloring easy to do with fonts?

**Comment by jfly** [comment]
Haha, good point. I meant per sticker coloring. Per icon coloring is definitely easier with a font.

**Comment by jbcm627** [comment]
Oh, that is a good idea too.

What about both; good svg icons and also a font?

**Comment by keemy** [comment]
yeh i mean either way coloring shouldnt be hard (it might be a bit faster to do with fonts). but like i was saying the main reason i haven't done anything is because i haven't been sure what to do for feet/oh/fmc/multibld

**Comment by jfly** [comment]
Another one http://fontello.com/

**Comment by FatBoyXPC** [comment]
Here's another service for it: https://icomoon.io/

This service also lets you create a project. When you download your project from them, it includes a json file with your project settings that makes importing it later real easy. I suggest just keeping the full zip though, and uploading it (if it's even ever necessary to import it in the future).

**Comment by lgarron** [comment]
I like the CubingChina ones a lot. I have some nitpicks (stuff laid over 3x3x3 should have a larger border, "xN" is not intuitive, I'd change the Megaminx layer size to be more traditional, the hand looks like a stop signal, and big cubes should also nave a number label), but they are fairly clear.
![events-icon](https://cloud.githubusercontent.com/assets/248078/5832994/4e541dca-a102-11e4-86e1-72fd2f9a8b35.png)

**Comment by lgarron** [comment]
For what it's worth, I was experimenting with outlines (to leave the stickers as lighter negative spaces) yesterday:

![wca-event-icons](https://cloud.githubusercontent.com/assets/248078/5833046/0228eb64-a103-11e4-8c5f-ee3a5e135e9e.png)

![img_7003](https://cloud.githubusercontent.com/assets/248078/5833047/05ac56e0-a103-11e4-96a8-8527171f1577.jpg)

**Comment by Baiqiang** [comment]
I like the border outlines. But it's not pretty when it becomes small.

![qq 20150121162125](https://cloud.githubusercontent.com/assets/2390434/5833073/8fe6c008-a189-11e4-851c-f9c444930020.png)

**Comment by lgarron** [comment]
> I like the border outlines. But it's not pretty when it becomes small.

Really? I think they actually look quite nice at that size (even without any tweaks for aliasing issues and line weights). The shape of each item is very clear.

If I squint and look at the CubingChina icons, they all turn into black squares.

(Not meant to be an attack, just a comparison of merits when they're scaled down.)

**Comment by Baiqiang** [comment]
> Really? I think they actually look quite nice at that size (even without any tweaks for aliasing issues and line weights). The shape of each item is very clear.

I meant they're more beautiful in the big size. Shapes are really clear. But some lines look a bit fuzzy.

**Comment by keemy** [comment]
I actually ended up trying all the linked websites and they all had problems with properly converting the svg files (usually lines ended up missing or something similar). I did however finish with making the feet/bld/fmc icons. which you can fully view here (https://www.dropbox.com/sh/pttm9mrwkopsnv5/AAAcOLeoFVSRpbZpGcNZbT2za?dl=0 each shows up twice because one it in illustrator format and the other is svg). I'm leaning towards the ones marked with a 2 at the end.

**Comment by FatBoyXPC** [comment]
Did you try dragging the icon around in icomoon? I had problems importing
some SVGs as well, but I was able to drag them around.

**Comment by keemy** [comment]
Err forgot OH but I'll do that in a few hours (probably will look like the feet one but with a hand instead of a foot)

**Comment by keemy** [comment]
uhh just tried dragging them around in icomoon and that didn't seem to help.

**Comment by FatBoyXPC** [comment]
Have you looked at the 6x6 and 7x7 cubes in a small font? My only complaint
is that to get 7x7 large enough to be obvious enough that it's 7x7, the 2x2
icon ends up way too big. Your thoughts?

**Comment by keemy** [comment]
Hmm I belive currently the 2x2 and 7x7 icons are used in the actual app on the live results pages and I felt they looked ok there. If there is a problem though I can modify the whitespace between the stickers so it can scale smaller.

**Comment by FatBoyXPC** [comment]
Without the 666 and 777 text, this isn't glaringly obvious to me:
https://imgur.com/IW7GhW5

**Comment by keemy** [comment]
hmm I see what you are saying. I think I can make it so they will be a little bit sharper when scaled down that far but its unlikely it will make a huge difference.

**Comment by FatBoyXPC** [comment]
Yeah, unfortunately, I don't have a good proposed solution to that problem.

**Comment by keemy** [comment]
they seem much nicer at 25px (vs the 18 they currently are at)

**Comment by FatBoyXPC** [comment]
Yeah, but 2x2 at 25px looks a bit absurd.

**Comment by keemy** [comment]
really? I felt it looked alright, if that is the only problem though I could just add some extra boarder around the 2x2.

**Comment by keemy** [comment]
K these should basically be the final ones https://www.dropbox.com/sh/0eymhj470rghkwi/AAApTPRxySOT-hTmAyQBjYrma#/ they are also up on the staging server now.

**Comment by lgarron** [comment]
I like those quite a lot! OH is especially clear for how simple it is.

The main thing I would change is to turn the clock into a single clock face
(like I did) so it's very easy to distinguish from 3x3x3.

Apart from that, I thin

**Comment by jbcm627** [comment]
Indeed, I like these too :+1:  I'll echo Lucas's comments for clock.  For 5x5+, as long as there is text next to the icon, I don't think it is a big deal; but this text does disappear some of the time.

**Comment by keemy** [comment]
Removing this from stage 1 milestone as they seem adequate for that.  

As for the feedback I was trying  numerals for 5-7 and it really looks terrible that coupled with the fact that the 5-7 still look very good on high dpi (such as newer phones) devices leave me to want to leave as is. As for the clock I don't really feel strongly for one way or another besides the fact that all other (speed) event are represented by the profile of the associated puzzle and changing the clock to what is suggested would break that consistency, that said if someone feels strongly enough about it feel free to change it.

As for the fonts, I'll be looking into this again at a later date but like i said none of the services suggested worked well for me so when I do look at it again (or someone else does) I imagine they will have to do it by hand.

**Comment by jbcm627** [comment]
Icon shapes look great :) 

Having the fonts done for phase 1 could still be nice though.  Currently the icons aren't visible on some pages due to color:
http://staging.live.jflei.com/manage/StarlightOpen2014/data-entry/555

**Comment by keemy** [comment]
Yeh I was aware of this color problem, which is why I didn't close this issue

**Comment by FatBoyXPC** [comment]
I got the font created with icomoon. Should be up soon!

**Comment by lgarron** [comment]
> As for the clock I don't really feel strongly for one way or another besides the fact that all other (speed) event are represented by the profile of the associated puzzle and changing the clock to what is suggested would break that consistency, that said if someone feels strongly enough about it feel free to change it.

I do feel strongly. I think it will definitely reduce confusion.

I can also make the opposite consistency argument: Megaminx doesn't show a profile, it shows a face, as do all the other puzzles. A single clock face is, of course, a single circle.

**Comment by keemy** [comment]
I disagree with the confusion and I misstated when I said profile when I meant face sorry for the confusion (though really this is all semantics and I believe you knew what I meant). 

Additionally I wouldn't consider a single circle a face anymore than I would consider a single sticker  of a 5x5 cube a face. That being said I still plan to merge your change because you seem to feel a lot more strongly about this I just wanted to document my disagreement.

**Comment by keemy** [comment]
Also @FatBoyXPC  got the font working and we put everything on https://github.com/cubing/icons so I'm going to close this issue (finally). And further discussion can happen over there.
