### ISSUE TITLE
View registered competitors

### ISSUE THREAD

**Issue by jfly** [cubing/ccm#116]
People are going to want to see who else is going to a competition. This blocks Phase 1, IMO.

**Comment by jbcm627** [comment]
Possible ideas:
 - Presumably this will be a table like www.cubingusa.com/usnationals2014/competitors.php.  Rather than static 'X's though, clicking them could jump to psych sheet / results.
 - Maybe icons to indicate position / round achieved?

**Comment by jfly** [comment]
Pushing to Phase 2, as this is only really useful if we're using CCM for registration, which is not the plan for the Hayward competition (thank you cubingusa!)

**Comment by jfly** [comment]
CCM is not going to be a registration platform (see https://github.com/cubing/ccm/issues/133#issuecomment-260444067). Closing.
