### ISSUE TITLE
Import wca/cubingusa/cubingchina registration information

### ISSUE THREAD

**Issue by jfly** [cubing/ccm#128]
(broken out from #115)

The wca already exports csv, and @jbcm627 said cubingusa could start doing so in order to save us from having to parse excel files.

I'm not actually convinced this is something we need to ever handle, but I'll put it on Phase 1 for now.

**Comment by jbcm627** [comment]
Well, this is certainly something competitions that have already started registration elsewhere, but want to use this system, will want to do.

Or maybe there's something funny they need to do for registration so they have their own system.

**Comment by jfly** [comment]
A pure js csv parser: http://papaparse.com/

**Comment by jfly** [comment]
Does anyone know how cubingchina competitions export their registration information?

**Comment by jfly** [comment]
Update: CubingUSA supports JSON export, and WCA website will soon as well. There's no need for us to mess around with excel or CSV.

In fact, CCM already supports importing registration JSON:

![image](https://cloud.githubusercontent.com/assets/277474/20280520/a33b4baa-aa61-11e6-977e-b36d7a97b2f4.png)

So there is really no work to do here, the user just needs to copy paste the JSON. Later on, we could look into making the importing more seamless, but that's definitely not needed for Phase 2. Closing this issue.
