### ISSUE TITLE
Arbitrary text/html input

### ISSUE THREAD

**Issue by jfly** [cubing/ccm#133]
As much as we want to be the facebook to cubingusa's myspace (with regards to how much customization we allow), the fact of the matter is that people do crazy stuff, and there's no way we'll be able to anticipate all of it.

Changing registration prices over time (#40) may be an example of this.

This will be used for the travel page (#132), the competition homepage, and the registration page. I think we can leave /events and /schedule alone.
## Analysis of fancy text editors

A list of wysiwyg editors can be found [here](https://www.drupal.org/node/596966) (cubingusa uses ckeditor).

More editors:
- [simplemde-markdown-editor](https://github.com/NextStepWebs/simplemde-markdown-editor) - Looks promising. See relevant [blog post](https://medium.com/code-musings/making-writing-markdown-a-piece-of-cake-for-non-technical-users-227e5a681a28#.i00740518).
- [EpicEditor](http://epiceditor.com/) - really slick markdown editor, but doesn't support [image uploads](https://github.com/OscarGodson/EpicEditor/issues/282)
  - [logdown](https://logdown.com/demo#top) - Looks similar to `inacho/bootstrap-markdown-editor`, but isn't free?
- [inacho/bootstrap-markdown-editor](https://github.com/inacho/bootstrap-markdown-editor) - Markdown editor, with support for image uploads!
- [Bootsty](http://bootsy-demo.herokuapp.com/) - seems kind of janky, managed to break it just by lightly clicking around
- [Froala WYSIWG](https://www.froala.com/wysiwyg-editor) - Looks gorgeous, but is not free and is editing html... markdown would be preferable.
- [remarkable](http://jonschlinkert.github.io/remarkable/demo/)
- [bootstrap-markdown](http://www.codingdrama.com/bootstrap-markdown/)
- [woofmark](http://bevacqua.github.io/woofmark/)
- [markdownify](http://tibastral.github.io/markdownify/)
- [griffin.editor](https://github.com/jgauffin/griffin.editor)
- [bootstrap-wysiwyg](http://mindmup.github.io/bootstrap-wysiwyg/)
- [summernote](https://github.com/summernote/summernote)
- [stackedit](https://stackedit.io/editor) - Lovely looking editor, but seems to be integrated into a full stack application we don't need? https://app.classeur.io seems to use the same editor somehow.

**Comment by FatBoyXPC** [comment]
Here's another one:
http://mindmup.github.io/bootstrap-wysiwyg/
Atmosphere link for above: https://atmospherejs.com/mcrider/bootstrap-wysiwyg

Atmosphere link for summernote:
https://atmospherejs.com/summernote/summernote

**Comment by jfly** [comment]
More editors:
- [Bootsty](http://bootsy-demo.herokuapp.com/) - seems kind of janky, managed to break it just by lightly clicking around
- EpicEditor - really slick markdown editor, but doesn't support [image uploads](https://github.com/OscarGodson/EpicEditor/issues/282)
- [Froala WYSIWG](https://www.froala.com/wysiwyg-editor) - Looks gorgeous, but is editing html... markdown would be preferable.
- [inacho/bootstrap-markdown-editor](https://github.com/inacho/bootstrap-markdown-editor) - Markdown editor, with support for image uploads!
- [logdown](https://logdown.com/demo#top) - Looks similar to `inacho/bootstrap-markdown-editor`, but isn't free?

**Comment by jfly** [comment]
Closing this, as CCM is *not* going to be a registration/competition hosting platform. We originally thought we would do this because CubingUSA was dying and had no clear replacement, but the WCA website is now under active development and will be able to provide a replacement for CubingUSA.
