### ISSUE TITLE
Adding or editing a registration with a duplicate name doesn't show a useful error

### ISSUE THREAD

**Issue by jfly** [cubing/ccm#136]
There's a message that shows up in the console, but ideally we'd show something on the modal. This such a corner case, we don't need to handle this for Phase 1.

**Comment by FatBoyXPC** [comment]
I actually kind of disagree on this. We would have to educate all the users of CCM about this strange behavior, which depending on how fast it takes off, could eat a lot of time. I believe simple-schema would actually handle this for us. Is there any reason why we aren't using it currently? Seeing that autoform and collection2 are both used, it actually surprised me to find out simple-schema isn't.

**Comment by FatBoyXPC** [comment]
I noticed in _collections.js that there is a userId defined for Registrations. Is this intentional? Is this due to a schema change? I am changing it to _id so that when I run the custom validator, I can see if we're editing the user that has the unique name we are trying to save.

**Comment by FatBoyXPC** [comment]
And that's now allowed because updating _id is not allowed. Bummer. I'll figure something out.

**Comment by jfly** [comment]
We have both a Users collection and a Registrations collection. There are a couple of reasons for this split, but one benefit is that you can have a Registration without requiring a corresponding account (a document in the Users collection). This is particularly useful for uploading results from JSON, and for walkin registrations.

Anyways, that userId you see in the Registrations collection is a pointer to the Users collection, so it wouldn't make sense to rename it to _id, as _id is the unique id of each document in the Registrations collection.

**Comment by FatBoyXPC** [comment]
Cool, glad that it's sensible. I still need a way to pull in the registration ID, though. Since it's not defined in the schema, I'm unsure at the moment how to pull that in. The idea I'm going for is findOne(), but if the id's match then we're editing the user, rather than adding.

**Comment by FatBoyXPC** [comment]
Just committed and pushed again. Let me know if this suits your fancy!

**Comment by FatBoyXPC** [comment]
Fixed with https://github.com/cubing/ccm/pull/153

**Comment by jfly** [comment]
:+1:
