### ISSUE TITLE
SEO Tasks

### ISSUE THREAD

**Issue by jbcm627** [cubing/ccm#152]
Dropping a note about this here.  It is important to show search engines rendered pages some of the time (well, perhaps all the time).  But this is especially important for pages with competition information on them, and perhaps the homepage.  I came across this:
https://meteorhacks.com/meteor-server-sider-rendering-for-seo-purpose.html

**Comment by jfly** [comment]
I'm not very knowledgeable about this, but I'm very interested to see how googlebot reacts to out live meteor side. My understanding is that googlebot *does* actually execute javascript now. I think @keemy  and @FatBoyXPC know more about this.

**Comment by jbcm627** [comment]
It looks like google is headed in that direction, but don't explicitly say they will render every page:
http://googlewebmastercentral.blogspot.com/2014/05/understanding-web-pages-better.html
Of course, I'm not sure how out of date that is now :) Other search engines seem less likely to run javascript:
http://www.bing.com/webmaster/help/webmaster-guidelines-30fba23a

I went ahead and fetched as google too. I'm not sure if all the errors are due to it not being in production mode?
![ccmonsoliton](https://cloud.githubusercontent.com/assets/964048/5900542/4e4fa2d8-a538-11e4-9f2a-9c3acc00a631.png)

**Comment by jfly** [comment]
How do you fetch as google? Can you try it against live.jflei.com?

**Comment by jfly** [comment]
I don't think we need to worry about SEO here, in fact, I'd rather that the WCA site get all the search engine juice.
