### ISSUE TITLE
Per competitor results page is racy

### ISSUE THREAD

**Issue by jfly** [cubing/ccm#171]

**Comment by jfly** [comment]
@limabeans, FYI. You've probably noticed tha the results page starts rendering before we've loaded all the results from the server. Note that our other routes don't have this behavior. This shouldn't happen because we use iron:router's [waitOn](https://github.com/iron-meteor/iron-router#loading-hook) mechanism.

**Comment by limabeans** [comment]
Hmmm yeah, I noticed that because sometimes the 2x2 results at the top would get rendered incorrectly. How do I fix it? Should waitOn be the competitorResults.js?

**Comment by jfly** [comment]
I am not able to reproduce this, going to optimistically close it.
