### ISSUE TITLE
Chrome will start blocking requests from the web to localhost

### ISSUE THREAD

**Issue by lgarron** [cubing/ccm#174]
https://crbug.com/378566 `Block sub-resource loads from the web to private networks and localhost`

This will presumably break:
![screenshot 2015-02-01 14 35 42](https://cloud.githubusercontent.com/assets/248078/5994218/a03eee14-aa1f-11e4-87ce-1a3a0f437388.png)

**Comment by jfly** [comment]
Am impressed you found this little hack :) 


This is only a cute little helpful thing ccm does, it still just provides a link to localhost, which I'm sure will continue to work fine.

Long term plan is to get tnoodle ported to c++ in the next year, depending on when ccm starts to wind down.
