### ISSUE TITLE
Items Scheduled for 30 minutes

### ISSUE THREAD

**Issue by FatBoyXPC** [cubing/ccm#183]
When I make an item scheduled for 30 minutes, I don't see the end time. See: https://imgur.com/FfvZ0Os

**Comment by Baiqiang** [comment]
Look at the file css/fullcalendar.css. From line 883 to line 912, the style of short mode is there. In short mode, the full time is hidden and only the start time is shown with the pseudo element :before.

**Comment by FatBoyXPC** [comment]
Wow, you replied fast! I was actually in the middle of creating another issue that's a requested feature. Nice find, I'll take a look at it and see what I feel is the best way to go about it.
