### ISSUE TITLE
Chat Rooms

### ISSUE THREAD

**Issue by FatBoyXPC** [cubing/ccm#188]
Competitors might be able to take advantage of a chat room. I envisions these rooms as being a 'per competition'. This would allow them to post in the chat room with something such as "I lost my cube, anybody know where it is?" or even "I need to borrow a NxNxN for my heat coming up. Can anybody help?"

Staff might also be able to take advantage of a chat room. We've previously been using GroupMe, but this would allow us to get rid of that extra app. We could possibly build this into Wingman?

**Comment by jfly** [comment]
Ah, this should be super easy to do with meteor =). Integrating with wingman would be tricky, since wingman is currently only speaking to ccm via the rest api. To do this well, we'd probably want wingman to drink the Meteor DDP stream directly.

**Comment by jfly** [comment]
Upon further reflection, I agree there is a problem here to solve, but I don't know if wingman/ccm should be solving it, so much as facilitating the use of an existing group chat service. Perhaps CCM could speak some api to groupme or facebook chat or someting else?

**Comment by FatBoyXPC** [comment]
Since it's almost trivial to do in meteor, is using fb/groupme really justified? We end up relying on a 3rd party for essentially no reason at that point, and we'll be requiring staff to create accounts on those services if they don't already have one.

If we set Wingman up to interface with Meteor's DDP, then that's just an added benefit that we get to have better 2 way communication :D

**Comment by jbcm627** [comment]
Ooh... yeah, this could be really useful for Staff.

**Comment by jfly** [comment]
Good points about creating an account. 

Crazy idea: what about automatically creating an irc channel for staff? Are there good mobile irc clients?

**Comment by FatBoyXPC** [comment]
If we do that, we need to make it invite only, but that's trivial. I know there are several clients, but I'm not sure what you would consider 'good'. While this is still a somewhat sustainable solution, we're still running into putting another app on a device, and now we need to educate the staff on how to use it. I think IRC is actually a much worse solution than FB Group Chat or GroupMe.

**Comment by patriciali** [comment]
I don't see the issue with forcing people to have accounts on some other service. I can count on one hand the number of people I know who don't have gmail/fb accounts, and they're all over the age of 50.

**Comment by jfly** [comment]
I'm starting to agree that putting this in CCM might be best.

WRT to creating accounts, maybe @Baiqiang can we give us a perspective on this from someone behind the Great Firewall.
