### ISSUE TITLE
Schedule should allow multiple single-attempt entries for a round

### ISSUE THREAD

**Issue by MikeHughey1** [cubing/ccm#197]
For fewest moves and for multiBLD, we need the ability to show more than one entry, one per attempt, for attempts within a single round.

**Comment by FatBoyXPC** [comment]
Right now, the way you can handle that is by adding a new event (the red bar). @jfly and I have actually discussed this a little bit, and I'm ok with the current workaround. I'm unsure how much of the scheduling portion would need refactored. Right now, each calendar event is looked at as a 'round'.

**Comment by MikeHughey1** [comment]
I figured that was an option, but it seems a little clunky, considering that it's the standard thing to separate the individual attempts.  And overall it certainly doesn't look so nice - perhaps we could allow a way to set the color on individual events?

I can see how changing from (an event = a round) would likely require some refactoring, though.

It seems like something that can wait until things are fully operational, but as is, although setting it up is MUCH nicer than in CubeComps, the schedule certainly looks a lot uglier than CubeComps at the moment.

You'll have to pardon me - I'll probably be knocking anything around here I see that's inferior to CubeComps.  I think if you want this thing to succeed (and I think it can - I think it's needed), you need to knock it out of the park in relation to CubeComps.  Otherwise, you'll probably only have a tool that gets used in the US (since CubeComps is decidedly less popular here than elsewhere), and gets ignored in the rest of the world.  CubeComps is awfully popular worldwide.  Ultimately, you want to match or beat anything CubeComps does unless it's due to performance issues.  (I do consider performance issues to be a good reason to be less "fancy" than CubeComps.)

**Comment by MikeHughey1** [comment]
Also, I noticed that when I went back and used the red bar to add new events on my two-day competition, I would drag them to the second day, then enter the data in the dialog, and then they would get placed in the first day of the schedule.  I was able to easily drag them back over to the second day, but it seemed weird that they moved to the first day after filling out the dialog box.

**Comment by FatBoyXPC** [comment]
>  perhaps we could allow a way to set the color on individual events

That's in the works, but I've been lazy about it :X I'm actually working on cleaning up some stuff before I continue to pound on the schedule. 

> the schedule certainly looks a lot uglier than CubeComps at the moment

There is also an open issue about icons on the schedule. I have taken that upon myself, and that has also taken a back seat to the cleanup I mentioned above. Other than no icons on the schedule, what is uglier about it?

> 'll probably be knocking anything around here I see that's inferior to CubeComps

That's all fine and dandy as it only helps improve CCM :) You aren't one to be destructively critical, so I don't think you'll hurt any feelings.

> placed in the first day of the schedule

Please create an issue on this! I have a gut feeling I know why this is the case, but I will certainly forget to do this if there isn't an issue on this :)

**Comment by MikeHughey1** [comment]
> Other than no icons on the schedule, what is uglier about it?
Well, the colors, the 3D shading (although I can certainly get over that one, and I think other people will too), and the fact that the events don't overlap in funny ways when you have more than one event at a time.  The overlapping here is a bit ugly.  Check mine to see what I mean.

Also, is there a way to control which is on the left and which is on the right?  I couldn't figure out how to do that.  In CubeComps, it's order-dependent based on how you set up the text file, so you can control how that works.  For instance, on my Indiana 2015 sample here, I wanted left and right columns swapped from 1 PM until dinner.  Of course, if you implement the other issue I already saw here for separate "rooms", that would solve that issue extremely nicely.  I'd recommend you solve that by simply implementing that issue.

**Comment by FatBoyXPC** [comment]
First: I edited your post to what seemed like the sensible place to get out of the quote. Please tell me if I changed the context of your post.

> events don't overlap in funny ways

Yeah, I've noticed that. I can't tell you right now how/why this is the case. I can, however, tell you that before we had the drag and drop UI, all the non scheduled rounds shared the space at the top, and they didn't overlap each other.

> is there a way to control which is on the left and which is on the right

Unfortunately, I do not know at this time. Maybe we should make an issue on overlapped calendar events. Rooms has also been discussed, but again, unknown amount of refactoring at play here. We made a bit of an (possibly incorrect) assumption that huge competitions will need the separate rooms feature.

#28 specifically addresses the rooms feature.

Also, see #21 where Jim posts several ideas for the schedule. As of now, that is not in the Phase 1 milestone.

**Comment by FatBoyXPC** [comment]
So, the package we used for the calendar is called [Full Calendar](http://fullcalendar.io/).

It seems like in their examples that the calendar events go from left to right alphabetically.

**Comment by MikeHughey1** [comment]
Thanks, that helps me understand some of the limitations.  I guess that just means we need to get creative with our workarounds.

**Comment by jbcm627** [comment]
Once there are multiple rooms, hopefully that will help the side-by-side issue.  It may be useful to have multiple calendar items for the multiple rooms case too... Maybe FMC needs to happen in several places simultaneously.

**Comment by jfly** [comment]
A few things:

- Please be careful to say "calendar event" any time you feel the urge to say "event". Event already has a specific meaning to us cubers =)
- CCM is focused primarily on making organizers happy. They're the only people who matter for adoption =). That said, I am a cuber, so I definitely do want the front end to be nice as well.

In terms of making the calendar prettier, I see two somewhat related options:

1. Rendering a calendar is easier than building an editable calendar. For the (uneditable) competitor facing calendar, we could render our own gorgeous calendar and not worry about any FullCalendar limitations/vagaries.
2. If we do do 1., we could eventually make it draggable and replace FullCalendar entirely.

**Comment by coder13** [comment]
Keep in mind for WCA site / data format.
