### ISSUE TITLE
Schedule "new events" get moved to the first day of a two-day competition

### ISSUE THREAD

**Issue by MikeHughey1** [cubing/ccm#198]
On the schedule, when using the red bar to add new events on my two-day competition, I would drag them to the second day, then enter the data in the dialog, and then they would get placed in the first day of the schedule. I was able to easily drag them back over to the second day, but it seemed weird that they moved to the first day after filling out the dialog box.

**Comment by jfly** [comment]
Interesting, it appears that dragging to the second day works for unscheduled wca events, but not for new red events?

**Comment by FatBoyXPC** [comment]
Yep, I have a sneaking suspicion of what is happening. Without looking at the code to refresh my memory, I think all I did was look at the time on the day that the event is dropped on, and didn't think to look at which day it was dropped on. This would have never happened had eventChange time stuff was able to be used in drop, but at the moment I can't remember why we weren't able to share that code (something to do with round time / startTime / durationMinutes I think).

**Comment by jfly** [comment]
See https://github.com/cubing/ccm/issues/222#issue-61871789 for a direct pointer to the relevant code.

**Comment by jfly** [comment]
It looks like @larspetrus fixed this as part of #235.
