### ISSUE TITLE
Add an unobtrusive sticky footer 

### ISSUE THREAD

**Issue by jfly** [cubing/ccm#205]
Example here: http://getbootstrap.com/examples/sticky-footer/. Lets just have it say "Powered by [CCM](https://github.com/cubing/ccm)".

Lets wait to do this until @FatBoyXPC has finished his css cleanup here: https://github.com/fatboyxpc/ccm/tree/less-cleanup.

**Comment by jbcm627** [comment]
Just to clarify, by sticky you mean "at the bottom of the page or off-screen below", not "always visible on-screen at the bottom of the page", right?

**Comment by jfly** [comment]
Yes, not always visible :)
