### ISSUE TITLE
Waitlist for competitions with competitor limits

### ISSUE THREAD

**Issue by KitClement** [cubing/ccm#212]
One frustration I have with CUSA is that with competitions that have a competitor limit, there is no good way to control what happens when a competitor finds out he/she cannot attend.  If there is no pre-payment option, it is possible that the organizer could close registration and open it temporarily to add a new competitor from an external waitlist, but for competitions with pre-payment, this is a mess.

Some system where competitors can register onto a waitlist and be notified when their registration is validated (and potentially need to pay a registration fee) would be a great feature.

**Comment by jbcm627** [comment]
Good idea. :+1:

**Comment by jbcm627** [comment]
These are irrelevant for CCM now, but it might be a good idea to add them to the WCA website?

**Comment by jfly** [comment]
Yep! The WCA website do already has waitlists, and we have issues for making it better: https://github.com/cubing/worldcubeassociation.org/issues?q=is%3Aopen+is%3Aissue+label%3Aregistration
