### ISSUE TITLE
competition limits (from article Z)

### ISSUE THREAD

**Issue by jbcm627** [cubing/ccm#213]
This could grow complicated, both backend and for competition organizers, so it would require a good UI.  But supporting regulations [Z2-Z5](https://www.worldcubeassociation.org/regulations/#article-Z-optional) would be neat.

 - [ ] #63 Z2) The organisation team may limit the number of events per competitor.
 - [ ] Z3) The organisation team may select competitors who directly qualify for certain rounds of certain events based on the results of specific previous competitions.
 - [ ] Z4) The organisation team may limit the number of competitors per event, on either a "first come first serve" basis or based upon qualification times or rankings in the WCA world rankings of a previously announced calendar date.
 - [ ] Z5) The organisation team may prohibit competitors from participating in specific combinations of events.

This would need to play well with #212.

**Comment by jfly** [comment]
Ohhhhh boy. This will definitely require some thinking and true love. I'm not opposed to this, but obviously not a priority right now. Maybe in a year, when everything works :)

**Comment by jbcm627** [comment]
Yeah, I don't think these should be a priority :)  I don't think these are commonly used, and organizers can always enforce these by hand (which is how things are currently done afaik).  But at some point it would be neat to offer these as options.

**Comment by KitClement** [comment]
I'm no programmer, but I think the simplest ones to implement that would be incredibly useful for organizers would be Z2 and Z5.  Z3 and Z4 seem rarely used to me, and I think just handling event restrictions and competitor limits would make most organizers very happy.

**Comment by jbcm627** [comment]
I think this is low priority, but not irrelevant. While these can be enforced during registration, it would still be good to enforce on the data-entry side as well.
