### ISSUE TITLE
Color of the homepage link does not match page background when active

### ISSUE THREAD

**Issue by jfly** [cubing/ccm#217]
On http://staging.live.jflei.com/:

![2015-03-11_369x288_laptor](https://cloud.githubusercontent.com/assets/277474/6612870/217280ce-c841-11e4-8316-54d75cdd9324.png)

Correct on https://live.cubing.net/:

![2015-03-11_287x209_laptor](https://cloud.githubusercontent.com/assets/277474/6612873/2c6daf08-c841-11e4-95dd-7d8f22a39009.png)

@FatBoyXPC, is this fallout from https://github.com/cubing/ccm/pull/210?

**Comment by jbcm627** [comment]
I'm going to put a note about this here because it might be related: the "plus" on the check-in page has disappeared as well.
![checkin](https://cloud.githubusercontent.com/assets/964048/6618758/9a23da86-c89b-11e4-8e07-e1a7d680ae98.png)
