### ISSUE TITLE
Make native date picker work reasonably on firefox

### ISSUE THREAD

**Issue by jfly** [cubing/ccm#220]
See http://caniuse.com/#search=date for the state of `<input type='date'>` support.

It's not important to me that we actually have a datepicker in firefox, but we should definitely display a helpful placeholder at the very least.

**Comment by jfly** [comment]
Text only for picking a date on firefox seems fine, but we also have datetime-local pickers now for competition registration open/close. We'll eventually need to figure something out for those, too.

**Comment by jbcm627** [comment]
I'm not enthusiastic about using browser's native date/time fields, as there are more user-friendly and prettier options. I mentioned this in #221, but what about something like this?
http://xdsoft.net/jqplugins/datetimepicker/

**Comment by jfly** [comment]
http://xdsoft.net/jqplugins/datetimepicker/ seems okay. I played around with it for a minute and have some minor nitpicks (seems like it doesn't handle locales, and it makes you type 2 digits for the hours part). None of those are reasons not to use it though, the reason I went with the native pickers is because they work with autoform's autosave. At some point, we can look into integrating http://xdsoft.net/jqplugins/datetimepicker/ with autoform. I found it pretty easy to do so with a different timepicker we're currently using (see https://github.com/jfly/ccm/commit/89c0a124f8c7d72d57617750fe38f6e5caad80a7#diff-dd40eb85707ef694e992d503300a8525R1)

**Comment by ddzoan** [comment]
Using the scroll wheel and having the mouse scroll over the input box causes the page to stop scrolling  and instead start scrolling through dates. GROSS.

This is for the 4th input box "DatePicker"

**Comment by ddzoan** [comment]
Ok, I resolved that issue by setting the option scrollInput to false.

**Comment by jfly** [comment]
Irrelevant now.
