### ISSUE TITLE
Registration open/close pickers only let you pick a date, not a time

### ISSUE THREAD

**Issue by jfly** [cubing/ccm#221]
We were originally using aldeed:autoform-bs-datetimepicker, but that proved too buggy for us.

We need to either let users pick a time, or provide sane defaults (@jbcm627, any opinions here?)

**Comment by jbcm627** [comment]
CubingUSA's default time is mm/dd/yyyy at 11:59 PM.  11:59 is less confusing than 12:00 AM next day.

What about something like this?
http://xdsoft.net/jqplugins/datetimepicker/
