### ISSUE TITLE
competition.html and competitions.html in ./templates, consider renaming?

### ISSUE THREAD

**Issue by limabeans** [cubing/ccm#231]
Pretty easy to get mixed up, I think

**Comment by jfly** [comment]
Hmm... we could move competitions into home?

**Comment by FatBoyXPC** [comment]
I would prefer that templates remain in the templates directory, but sub
directories based off sections of the app wouldn't hurt. We could also
rename competitions to competitions-list or something, as that is a bit
more descriptive

**Comment by jfly** [comment]
Good suggestions, @FatBoyXPC. Agreed that the templates should stay in the templates/ folder, unless there's a compelling reason to put a template somewhere else (I recently broke this rule in https://github.com/jfly/ccm/commit/e585355cd7ec83caea3fdbf46d0fa7d42fc99d98#diff-dd40eb85707ef694e992d503300a8525R1).

@limabeans, please feel free to make whatever change here you belive is best.

**Comment by FatBoyXPC** [comment]
When the template belongs to a separate package then I think that makes
sense to put it there. I was meaning for CCM specific templates.
