### ISSUE TITLE
Social media stuff

### ISSUE THREAD

**Issue by jbcm627** [cubing/ccm#236]
A few ideas:
- Consider a posting feature (something @MikeHughey1 has commonly done with his websites (eg, see the bottom [here](http://koii.cubingusa.com/Indiana2015/index.php))
- Standard links to SS and WCA (?) page(s)
- Facebook/g+/etc share links?

**Comment by jfly** [comment]
Do not care =) I'd rather add these features as people ask for them, rather than trying to anticipate them.
