### ISSUE TITLE
It's possible to drag an event before midnight and lose it forever

### ISSUE THREAD

**Issue by jfly** [cubing/ccm#245]
This happens on <https://live.cubing.net/manage/StarlightOpen2014/schedule>.

**Comment by larspetrus** [comment]
You can also lose events by changing the start and end times of the competition.

**Comment by jfly** [comment]
Yeah. Once upon I time, such actions would cause an event to be considered "unscheduled", I don't know when that changed.

**Comment by larspetrus** [comment]
I, uh, removed it in my cleanups. The existing code was a mess, but the replacement wasn't trivial, so it's left as a TODO.

Both these things can probably be solved by the same code.
