### ISSUE TITLE
OAuth with WCA website doesn't give us country, gender, dob

### ISSUE THREAD

**Issue by jfly** [cubing/ccm#259]
Currently, worldcubeassociation.org doesn't expose country, gender, or dob over OAuth. If we want to support registration on CCM (something that might be up in the air, perhaps we'll move registration directly to the WCA website...), then we'll need these fields somehow. Definitely not a priority for Phase 1a.

**Comment by jfly** [comment]
The `/me` route has been updated in https://github.com/cubing/worldcubeassociation.org/commit/d79bfabc330e7c7995b58e840e2aeb2d9f681591.

**Comment by jbcm627** [comment]
Checking up on this - it looks like my birthdate isn't being imported correctly:

![capture](https://cloud.githubusercontent.com/assets/964048/14904707/1fa13344-0d78-11e6-89b3-43be348892b9.PNG)
