### ISSUE TITLE
Rename "hard cutoff" to "time limit" as per WCA regulations

### ISSUE THREAD

**Issue by jfly** [cubing/ccm#283]
We use the term "hard cutoff", which isn't defined anywhere in the regulations, the correct term is [time limit](https://www.worldcubeassociation.org/regulations/#A1a). I think it's okay to continue calling "cutoff" a "soft cutoff" (technically just ["cutoff"](https://www.worldcubeassociation.org/regulations/#9g)) to avoid confusion with the WCA regulation's other kind of [cutoff](https://www.worldcubeassociation.org/regulations/#9p2) (for advancing to next rounds)), however.

I think this actually is a priority for Phase 1a, to avoid confusion.

**Comment by viroulep** [comment]
It remains a few occurrences of soft/hard:
- [here](https://github.com/cubing/ccm/blob/9d27a36ceae3f9405153b71a6dcd868170fec3e1/client/pages/competitionEvents.jsx#L41-L42)
- and [here](https://github.com/cubing/ccm/blob/9d27a36ceae3f9405153b71a6dcd868170fec3e1/templates/editEvents.html#L52-L53)

I'd just go for simple "Cutoff"/"Time limit" in these cases.
