### ISSUE TITLE
Issues detected during Atomic Cubing 2016

### ISSUE THREAD

**Issue by jfly** [cubing/ccm#293]
- [ ] Pressing enter to select someone's name focuses you on the second input
- [ ] The data entry well doesn't affix smoothly
  - [ ] *Especially* when on mobile
- [ ] The hollow bullet fills in *even* when your time is not yet saved to the server
  - [ ] The database save seems to occur when pressing enter on the last jChester, not when pressing enter on the save button
- [ ] Cubecomps style warnings about solve better than current WR, or best solve wayyyyy better than worst solve
- [ ] Display the latest open round by default? https://live.cubing.net/AtomicCubing2016/results/333/ redirects to finals
- [ ] People without results in first round are in no discernable order (@kitclement and @AlexMaass)
- [ ] Better handling of rounds with cutoffs (all 5 show up, and they don't disappear even after they didn't make the cutoff)
- [x] @coder13 could not log in via WCA OAuth because he has a password account
- [ ] Clicking the save button doesn't visibly do anything
- [ ] How do cumulative cutoffs work with DNFs?
- [ ] Vertically align everything, despite parens (@AlexMaass)
- [ ] Simultaneous data entry sometimes clears out current data entry well! Yikesss
- [ ] Deleting a round with results leaves a modal backdrop you can't get past
- [ ] Per competitor page doesn't show all results (https://live.cubing.net/AtomicCubing2016/results/byname/Jeremy+Fleischman)

**Comment by AlexMaass** [comment]
I'll add to the list of issues

-the names of people whose times aren't inputted yet are not sorted alphabetically

**Comment by coder13** [comment]
Podium page looks weird.
https://github.com/cubing/ccm/issues/294

**Comment by FatBoyXPC** [comment]
mbld results doesn't show solved/attempted. It only shows the time. See: http://i.imgur.com/V4B9t5X.png
