### ISSUE TITLE
Rankings with ties are not handled correctly

### ISSUE THREAD

**Issue by jfly** [cubing/ccm#311]
See

![image](https://cloud.githubusercontent.com/assets/277474/14944743/fbda85a0-0fb1-11e6-95cd-2d0601752e36.png)

Relevant code here: https://github.com/cubing/ccm/blob/master/both/collections/round.js#L124-L126.

I really suck at this, as @jonatanklosko knows =) https://github.com/cubing/worldcubeassociation.org/pull/437/files

**Comment by jonatanklosko** [comment]
I'm not familiar with this technology, but I think this should help:
```javascript
    if(!tied) {
      position = i + 1;
    }
```
