### ISSUE TITLE
unable to resolve "meteor" in presets of /home/jeremy/gitting/ccm/.babelrc warning

### ISSUE THREAD

**Issue by jfly** [cubing/ccm#328]
```
Warning: unable to resolve "meteor" in presets of /home/jeremy/gitting/ccm/.babelrc
```

**Comment by coder13** [comment]
Easy fix to this is to push the .babelrc file I have on my computer so you can have it too

**Comment by coder13** [comment]
https://www.npmjs.com/package/babel-preset-meteor
this probably needs to be added to the package.json

**Comment by coder13** [comment]
Can this be reproduced?
