### ISSUE TITLE
/editSchedule route doesn't exist

### ISSUE THREAD

**Issue by jfly** [cubing/ccm#334]
Maybe this is going to move over to the WCA website... maybe we already have an issue for this, but this is specific to the Overhaul milestone.

**Comment by coder13** [comment]
And we don't need it also.

**Comment by coder13** [comment]
But I still need to remove the tab

**Comment by coder13** [comment]
And now I can close.

**Comment by coder13** [comment]
Reopening cause It turns out I'm not done.
Everything related to editSchedule needs to be purged.
