### ISSUE TITLE
check-in page issues

### ISSUE THREAD

**Issue by jfly** [cubing/ccm#341]
- [x] MODALS (@coder13 knows what this means)
- [x] When clicking the wrench and when clicking the add button: "Warning: Unknown prop `closeButton` on <div> tag." this is probably the reason why the close button doesn't work
- [x] When attempting to delete a registration: "Uncaught RangeError: Maximum call stack size exceeded."
- [x] Import button is a lowercase "i"

**Comment by coder13** [comment]
MODALS means to make sure we're using modals the same way throughout the project future me.

**Comment by coder13** [comment]
Looks like we actually still use autoform for the edit registration modal which causes some problems when trying to fix the 2nd and 3rd issues. We need to make sure we know how to properly integrate it or replace it to resolve those.

**Comment by coder13** [comment]
https://github.com/makeusabrew/bootbox/issues/183
reason for the Maximum call stack size exceeded error
