### ISSUE TITLE
Organizers need some way of contacting competitors

### ISSUE THREAD

**Issue by jfly** [cubing/ccm#44]
mailto links seem like they only scale up to ~500 emails before you start running into limits. It would probably be best and most reliable to give organizers a textbox and use mandrill for this.

**Comment by coder13** [comment]
Vague, irrelevant as this should be done on the wca site?

Although a way to contact competitors during a comp would be interesting.

**Comment by jfly** [comment]
Yeah, during competition contact would be awesome, but email probably isn't the way we want to do that? Closing this issue.
