### ISSUE TITLE
Use autoform's "autosave" wherever possible, rather than submit and reset buttons

### ISSUE THREAD

**Issue by jfly** [cubing/ccm#94]
I just talked with @jbcm627 about this, and that seems like the best (rather than cluttering the ui with save buttons).

We should eventually indicate the state of these fields, through either a colored border or a spinning icon.

**Comment by FatBoyXPC** [comment]
Links to relevant issues for AutoForm and autoform-bs-datepicker.

AutoForm: https://github.com/aldeed/meteor-autoform-bs-datetimepicker/issues/3

AutoForm-bs-datepicker: https://github.com/aldeed/meteor-autoform-bs-datepicker/issues/11

**Comment by coder13** [comment]
Do we want to switch to autosave vs save buttons entirely? I'm rewriting an awful lot of forms so this would be good to know.

**Comment by jfly** [comment]
I'm a pretty big fan of autosave, especially in a meteor context.

**Comment by jbcm627** [comment]
Autosave does seem like a good idea when possible.

But, there may be some cases for which autosave isn't a good idea, for example when information entered in a partially complete state results in incorrect information being displayed elsewhere.

There are also cases where changes would affect other data (eg, changing round formats for open rounds), some sort of warning/confirmation should happen before autosaving.

**Comment by jfly** [comment]
I'm going to close this as we're going to have to deal with autosaving forms as part of the ongoing [Overhaul](https://github.com/cubing/ccm/milestone/7).
