### ISSUE TITLE
Add support for soft and hard cutoffs to data entry

### ISSUE THREAD

**Issue by jfly** [cubing/ccm#97]
hard cutoffs - We should add *warnings* for times that don't meet the hard cutoff, but I do want to allow them.

soft cutoffs - Should we should dynamically hide/show all the jChesters for a Result based on if it made the soft cutoff, or should we just show a warning? I think there's a good argument for just showing a warning.

I believe showing warnings is better than disabling functionality, because we need to handle the case where cutoffs become more or less lenient *anyways*.

**Comment by jbcm627** [comment]
Personally I prefer warnings - and perhaps not allowing WCA exports for things that are certainly illegal?

**Comment by shelchang** [comment]
I would prefer warnings for soft cutoffs, and also possibly being able to change soft cutoffs after some results have been entered if they don't affect current results.

**Comment by jfly** [comment]
For sure, we're going to allow changing soft cutoffs no matter what, even if it does cause warnings. They'll have to deal with them when they export to the wca.
